using UnitsDrafts;

Barracks barracks = new Barracks();
Footman footman1 = barracks.CreateFootman();
Footman footman2 = barracks.CreateFootman();
Peasant peasant = barracks.CreatePeasant();
Archer archer = barracks.CreateArcher();
Cleric cleric = barracks.CreateCleric();
BuildingFactory factory = new BuildingFactory();
List<Archer> ArcherList = new List<Archer>();
ArcherList.Add(archer);
WatchingTower MegaUberBashnya = factory.BuildTower(ArcherList, 1);
MegaUberBashnya.ShowInfo();
footman1.InflictDamage(peasant);
peasant.BaseInfo();
footman1.InflictDamage(peasant);
peasant.BaseInfo();
cleric.Heal(peasant);
peasant.BaseInfo();
footman1.InflictDamage(peasant);
peasant.BaseInfo();
cleric.Heal(peasant);
peasant.BaseInfo();
footman1.InflictDamage(peasant);
peasant.BaseInfo();
footman1.InflictDamage(footman2);
footman1.InflictDamage(footman2);
footman1.InflictDamage(footman2);
footman1.InflictDamage(footman2);
footman1.InflictDamage(footman2);
footman1.InflictDamage(footman2);
footman1.InflictDamage(footman2);
footman2.BaseInfo();
footman2.InflictDamage(footman1);
footman1.BaseInfo();